CREATE TABLE IF NOT EXISTS meals (
    id INTEGER PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    image TEXT NOT NULL,
    summary TEXT NOT NULL,
    instructions TEXT NOT NULL,
    creator TEXT NOT NULL,
    creator_email TEXT NOT NULL
);

INSERT INTO meals (slug, title, image, summary, instructions, creator, creator_email) VALUES
('juicy-cheese-burger', 'Juicy Cheese Burger', '/images/burger.jpg', 'A mouth-watering burger with a juicy beef patty and melted cheese, served in a soft bun.', '1. Prepare the patty:\nMix 200g of ground beef with salt and pepper. Form into a patty.\n\n2. Cook the patty:\nHeat a pan with a bit of oil. Cook the patty for 2-3 minutes each side, until browned.\n\n3. Assemble the burger:\nToast the burger bun halves. Place lettuce and tomato on the bottom half. Add the cooked patty and top with a slice of cheese.\n\n4. Serve:\nComplete the assembly with the top bun and serve hot.', 'John Doe', 'johndoe@example.com'),
('spicy-curry', 'Spicy Curry', '/images/curry.jpg', 'A rich and spicy curry, infused with exotic spices and creamy coconut milk.', '1. Chop vegetables:\nCut your choice of vegetables into bite-sized pieces.\n\n2. Sauté vegetables:\nIn a pan with oil, sauté the vegetables until they start to soften.\n\n3. Add curry paste:\nStir in 2 tablespoons of curry paste and cook for another minute.\n\n4. Simmer with coconut milk:\nPour in 500ml of coconut milk and bring to a simmer. Let it cook for about 15 minutes.\n\n5. Serve:\nEnjoy this creamy curry with rice or bread.', 'Max Schwarz', 'max@example.com'),
('homemade-dumplings', 'Homemade Dumplings', '/images/dumplings.jpg', 'Tender dumplings filled with savory meat and vegetables, steamed to perfection.', '1. Prepare the filling:\nMix minced meat, shredded vegetables, and spices.\n\n2. Fill the dumplings:\nPlace a spoonful of filling in the center of each dumpling wrapper. Wet the edges and fold to seal.\n\n3. Steam the dumplings:\nArrange dumplings in a steamer. Steam for about 10 minutes.\n\n4. Serve:\nEnjoy these dumplings hot, with a dipping sauce of your choice.', 'Emily Chen', 'emilychen@example.com'),
('classic-mac-n-cheese', 'Classic Mac n Cheese', '/images/macncheese.jpg', "Creamy and cheesy macaroni, a comforting classic that's always a crowd-pleaser.", '1. Cook the macaroni:\nBoil macaroni according to package instructions until al dente.\n\n2. Prepare cheese sauce:\nIn a saucepan, melt butter, add flour, and gradually whisk in milk until thickened. Stir in grated cheese until melted.\n\n3. Combine:\nMix the cheese sauce with the drained macaroni.\n\n4. Bake:\nTransfer to a baking dish, top with breadcrumbs, and bake until golden.\n\n5. Serve:\nServe hot, garnished with parsley if desired.', 'Laura Smith', 'laurasmith@example.com'),
('authentic-pizza', 'Authentic Pizza', '/images/pizza.jpg', 'Hand-tossed pizza with a tangy tomato sauce, fresh toppings, and melted cheese.', '1. Prepare the dough:\nKnead pizza dough and let it rise until doubled in size.\n\n2. Shape and add toppings:\nRoll out the dough, spread tomato sauce, and add your favorite toppings and cheese.\n\n3. Bake the pizza:\nBake in a preheated oven at 220°C for about 15-20 minutes.\n\n4. Serve:\nSlice hot and enjoy with a sprinkle of basil leaves.', 'Mario Rossi', 'mariorossi@example.com'),
('wiener-schnitzel', 'Wiener Schnitzel', '/images/schnitzel.jpg', 'Crispy, golden-brown breaded veal cutlet, a classic Austrian dish.', '1. Prepare the veal:\nPound veal cutlets to an even thickness.\n\n2. Bread the veal:\nCoat each cutlet in flour, dip in beaten eggs, and then in breadcrumbs.\n\n3. Fry the schnitzel:\nHeat oil in a pan and fry each schnitzel until golden brown on both sides.\n\n4. Serve:\nServe hot with a slice of lemon and a side of potato salad or greens.', 'Franz Huber', 'franzhuber@example.com'),
('fresh-tomato-salad', 'Fresh Tomato Salad', '/images/tomato-salad.jpg', 'A light and refreshing salad with ripe tomatoes, fresh basil, and a tangy vinaigrette.', '1. Prepare the tomatoes:\nSlice fresh tomatoes and arrange them on a plate.\n\n2. Add herbs and seasoning:\nSprinkle chopped basil, salt, and pepper over the tomatoes.\n\n3. Dress the salad:\nDrizzle with olive oil and balsamic vinegar.\n\n4. Serve:\nEnjoy this simple, flavorful salad as a side dish or light meal.', 'Sophia Green', 'sophiagreen@example.com');
